FROM node:22-alpine AS build
WORKDIR /app
ENV NODE_OPTIONS=--max-old-space-size=384
COPY package.json package-lock.json ./
RUN npm install --no-audit --no-fund --legacy-peer-deps
COPY . .
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_CONFIRM_WORKSPACE_KEY
ARG VITE_CONFIRM_MODE=production
ARG VITE_CONFIRM_PUBLIC_URL=https://confirm.relpdev.uk
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_CONFIRM_WORKSPACE_KEY=$VITE_CONFIRM_WORKSPACE_KEY
ENV VITE_CONFIRM_MODE=$VITE_CONFIRM_MODE
ENV VITE_CONFIRM_PUBLIC_URL=$VITE_CONFIRM_PUBLIC_URL
ENV VITE_AUTH_ENABLED=false
ENV NITRO_PRESET=node-server
RUN npm run build:server

FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=8080
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_CONFIRM_WORKSPACE_KEY
ARG VITE_CONFIRM_PUBLIC_URL=https://confirm.relpdev.uk
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_CONFIRM_WORKSPACE_KEY=$VITE_CONFIRM_WORKSPACE_KEY
ENV VITE_CONFIRM_PUBLIC_URL=$VITE_CONFIRM_PUBLIC_URL
ENV SUPABASE_URL=$VITE_SUPABASE_URL
ENV SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV CONFIRM_WORKSPACE_KEY=$VITE_CONFIRM_WORKSPACE_KEY
ENV CONFIRM_PUBLIC_URL=$VITE_CONFIRM_PUBLIC_URL
COPY --from=build /app/.output .output
EXPOSE 8080
CMD ["node", ".output/server/index.mjs"]
