FROM node:22-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_CONFIRM_WORKSPACE_KEY
ARG VITE_CONFIRM_MODE=production
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_CONFIRM_WORKSPACE_KEY=$VITE_CONFIRM_WORKSPACE_KEY
ENV VITE_CONFIRM_MODE=$VITE_CONFIRM_MODE
ENV VITE_AUTH_ENABLED=false
ENV NITRO_PRESET=node-server
RUN npm run build:server

FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=8080
COPY --from=build /app/.output .output
EXPOSE 8080
CMD ["node", ".output/server/index.mjs"]
